export const GENERAL_INFORMATION_INPUTS = [
  {
    label: "Name",
    type: "text",
    name: "name",
    placeholder: "Enter Patient's name",
  },
  {
    label: "Age",
    type: "number",
    name: "age",
    placeholder: "Enter patient's age",
  },
  {
    label: "Email",
    type: "email",
    name: "email",
    placeholder: "Enter patient's email",
  },
  {
    label: "Phone",
    type: "tel",
    name: "phone",
    placeholder: "Enter patient's phone number",
  },
  {
    label: "Address",
    type: "text",
    name: "address",
    placeholder: "Enter patient's address",
  },
  {
    label: "Insurance Name",
    type: "text",
    name: "insurance_name",
    placeholder: "Enter insurance name",
  },
  {
    label: "Insurance ID",
    type: "text",
    name: "insurance_id",
    placeholder: "Enter insurance ID",
  },
  {
    label: "Relationship to Insured",
    type: "text",
    name: "relationship_to_insured",
    placeholder: "Enter relationship to insured",
  },
  {
    label: "Symptoms",
    type: "text",
    name: "symptoms",
    placeholder: "Enter symptoms",
  },
];

export const MEDICAL_INFORMATION_INPUTS = [
  {
    label: "Blood Pressure (120/60)",
    type: "text",
    name: "blood_pressure",
    placeholder: "Enter patient's blood pressure",
  },
  {
    label: "Blood Glucose",
    type: "text",
    name: "blood_glucose",
    placeholder: "Enter patient's blood glucose",
  },
  {
    label: "Heart Rate",
    type: "text",
    name: "heart_rate",
    placeholder: "Enter patient's heart rate",
  },
  {
    label: "Body Temperature",
    type: "text",
    name: "body_temperature",
    placeholder: "Enter patient's body temperature",
  },
  {
    label: "Oxygen Saturation",
    type: "text",
    name: "oxygen_saturation",
    placeholder: "Enter patient's oxygen saturation",
  },
  {
    label: "Respiratory Rate",
    type: "text",
    name: "respiratory_rate",
    placeholder: "Enter patient's respiratory rate",
  },
];

export const THRESHOLDS_INPUTS = [
  {
    label: "Blood Pressure Threshold",
    subLabelOne: "120/80",
    subLabelTwo: "140/90",
    type: "text",
    nameOne: "blood_pressure_threshold_low",
    nameTwo: "blood_pressure_threshold_high",
    placeholder: "Enter patient's blood pressure",
  },
  {
    label: "Blood Glucose Threshold",
    subLabelOne: "Low",
    subLabelTwo: "High",
    type: "text",
    nameOne: "blood_glucose_threshold_low",
    nameTwo: "blood_glucose_threshold_high",
    placeholder: "Enter patient's blood glucose",
  },
  {
    label: "Heart Rate",
    subLabelOne: "Low",
    subLabelTwo: "High",
    type: "text",
    nameOne: "heart_rate_threshold_low",
    nameTwo: "heart_rate_threshold_high",
    placeholder: "Enter patient's heart rate",
  },
  {
    label: "Body Temperature",
    subLabelOne: "Low",
    subLabelTwo: "High",
    type: "text",
    nameOne: "body_temperature_threshold_low",
    nameTwo: "body_temperature_threshold_high",
    placeholder: "Enter patient's body temperature",
  },
  {
    label: "Oxygen Saturation",
    subLabelOne: "Low",
    subLabelTwo: "High",
    type: "text",
    nameOne: "oxygen_saturation_threshold_low",
    nameTwo: "oxygen_saturation_threshold_high",
    placeholder: "Enter patient's oxygen saturation",
  },
  {
    label: "Respiratory Rate",
    subLabelOne: "Low",
    subLabelTwo: "High",
    type: "text",
    nameOne: "respiratory_rate_threshold_low",
    nameTwo: "respiratory_rate_threshold_high",
    placeholder: "Enter patient's respiratory rate",
  },
];
